name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 或者你使用的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 更新到 v3

    - name: Setup Node.js
      uses: actions/setup-node@v3  # 更新到 v3
      with:
        node-version: '20'  # 使用 Node.js 版本 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist